apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fvcy2cljr-go 
  janus-idp.io/tekton: fvcy2cljr-go
  backstage.io/kubernetes-id: fvcy2cljr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fvcy2cljr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  